import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en" className="w-full h-[100%]">
      <body className={`${inter.className} w-full h-full border flex flex-col`}>
        <nav className="h-[79px] w-full flex items-center justify-between sm:px-[70px] px-[40px]">
          <Image src="/logo.svg" width={70} height={24} alt="Logo" />
          <div className="items-center gap-[64px] hidden sm:flex">
            <div className="cursor-pointer border-b-transparent border-b-2 flex items-center justify-center h-[23px] hover:border-b-2 transition-all duration-150 ease-in-out hover:border-b-[#61BFAD]">
              Movies
            </div>
            <div className="cursor-pointer border-b-transparent border-b-2 flex items-center justify-center h-[23px] hover:border-b-2 transition-all duration-150 ease-in-out hover:border-b-[#61BFAD]">
              Tv Shows
            </div>
            <Avatar>
              <AvatarImage className="h-[48px] w-[48px]" src="https://github.com/shadcn.png" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          </div>
        </nav>
        <main className="w-full h-full bg-[#F9F7E8] px-[52px] py-[27px] overflow-y-auto">{children}</main>
      </body>
    </html>
  );
}
