import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Toaster } from '@/components/ui/toaster';
import Navbar from './_components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en" className="w-full h-full">
      <body className={`${inter.className} w-full h-[100%] border flex flex-col`}>
        <Navbar />
        <main className="w-full bg-[#F9F7E8] flex h-[calc(100%-79px)]">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
